import os
import sys
import sphinx_bootstrap_theme
sys.path.insert(0, os.path.abspath('../'))


# -- Project information -----------------------------------------------------

project = 'python-qgenda'
copyright = '2019, JP Jorissen'
author = 'JP Jorissen'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

html_theme_options = {
    # Set the name of the project to appear in the sidebar
    "project_nav_name": "Python QGenda",
    # Currently, the supported themes are:
    # - Bootstrap 2: https://bootswatch.com/2
    # - Bootstrap 3: https://bootswatch.com/3
    'bootswatch_theme': "united",

    # Choose Bootstrap version.
    # Values: "3" (default) or "2" (in quotes)
    'bootstrap_version': "3",
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None
html_static_path = ['_static']
htmlhelp_basename = 'python-qgendadoc'
latex_elements = {
}

latex_documents = [
    (master_doc, 'python-qgenda.tex', 'python-qgenda Documentation',
     'JP Jorissen', 'manual'),
]

man_pages = [
    (master_doc, 'python-qgenda', 'python-qgenda Documentation',
     [author], 1)
]

texinfo_documents = [
    (master_doc, 'python-qgenda', 'python-qgenda Documentation',
     author, 'python-qgenda', 'One line description of project.',
     'Miscellaneous'),
]


epub_title = project

epub_exclude_files = ['search.html']
